bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
  config_file:
    - config/_bookdown.yml
    - config/_output.yml
  
bookdown::epub_book: default
  config_file:
    - config/_bookdown.yml
    - config/_output.yml

bookdown::bs4_book:
  css: style.css
  theme:
    primary: "#096B72"
  repo:
  config_file:
    - config/_bookdown.yml
    - config/_output.yml


