# config.yml

heatmaps:
  - correlation

clusters:
  - hclusters

barplots:
  - vbars
  - hbars
  - circular

boxplots:
  - boxplots
  - violin
  - jitters
  - strip

ordinations:
  - pca
  - pcoa
  - nmds

distances:
  - jaccard
  - thetayc
  - bray

phylotrees:
  - newick

bookdown:
  - html
  - pdf
  - bs4

rmarkdown:
  - docx
  - html
  - pdf
